title: Resume
url: "https://dooyeoung.github.io/"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: ""
footer_text: "dooyeoung.ryu@gmail.com"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
# - name: "Post"
#   link: "post"